#!/usr/bin/env python3
"""Generates the basis/grid tables and the reference values the Rust tests check against.

Nothing in `dft-core` may contain numbers typed from memory: every table and
every expected value either comes out of this script or is derived
independently inside the test itself.

Outputs:
  crates/dft-core/src/basis/sto3g_data.rs    STO-3G contractions for H-Ar
  crates/dft-core/src/basis/b631gs_data.rs   6-31G* contractions for H-Ar
  crates/dft-core/src/grid/lebedev_data.rs   Lebedev-Laikov angular grids
  crates/dft-core/tests/data/*.json          reference integrals, XC values, energies
  web/src/records/units.json                 Hartree -> kJ/mol, for the structure log

Usage:
  python3 -m venv .venv && .venv/bin/pip install pyscf
  .venv/bin/python scripts/gen_reference.py
"""

from __future__ import annotations

import json
import random
from pathlib import Path

import numpy as np
import scipy
from scipy import constants
from pyscf import dft, gto
from pyscf.data.elements import ELEMENTS
from pyscf.dft import gen_grid

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "crates" / "dft-core" / "tests" / "data"
WEB = ROOT / "web" / "src"

# Angular grid orders the engine embeds; the pruning scheme picks among these.
LEBEDEV_POINTS = [26, 50, 110, 194, 302]

# A dense grid makes the DFT reference energies essentially grid-converged, so a
# disagreement in the Rust tests points at the functional or the integrals
# rather than at quadrature noise.
REFERENCE_GRID_LEVEL = 9

SEED = 20260918


def f(x: float) -> str:
    """Round-trippable float literal."""
    return repr(float(x))


# --------------------------------------------------------------------------
# Units for the web side
# --------------------------------------------------------------------------


def write_units() -> None:
    """The conversion the structure log shows energies in.

    The interface never shows a total energy in Hartree next to another one:
    what a class compares is how much deeper one shape is than another, and that
    is a chemist's number, kJ/mol. The factor is one mole of Hartrees, and like
    every other constant here it is generated rather than typed.
    """
    hartree, unit, uncertainty = constants.physical_constants["Hartree energy"]
    payload = {
        "_comment": (
            "GENERATED by scripts/gen_reference.py. Do not edit by hand. "
            "One Hartree per particle, in kilojoules per mole."
        ),
        "source": (
            f"scipy.constants {scipy.__version__}: "
            "physical_constants['Hartree energy'] and Avogadro (CODATA)"
        ),
        "hartreeEnergy": {"value": hartree, "unit": unit, "uncertainty": uncertainty},
        "avogadro": constants.Avogadro,
        "hartreeToKilojoulesPerMole": hartree * constants.Avogadro / 1000.0,
    }
    path = WEB / "records" / "units.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")
    print(f"wrote {path.relative_to(ROOT)}")


# --------------------------------------------------------------------------
# Basis-set tables
# --------------------------------------------------------------------------


def write_basis_table(pyscf_name: str, static: str, header: list[str], filename: str) -> None:
    """One `[&[ShellDef]; 18]` table for H-Ar, shells in PySCF's order.

    Every row PySCF loads is `[exponent, coefficient]`: neither table here is
    generally contracted (an SP shell arrives already split into s and p), so a
    shell is exactly one `ShellDef`. A generally contracted basis would need a
    loop over coefficient columns, and the assert says so rather than silently
    keeping the first.
    """
    lines = header + [
        "",
        "use super::ShellDef;",
        "",
        "/// Shell definitions for each element, indexed by `z - 1`.",
        f"pub static {static}: [&[ShellDef]; 18] = [",
    ]
    for z in range(1, 19):
        symbol = ELEMENTS[z]
        shells = gto.basis.load(pyscf_name, symbol)
        lines.append(f"    // {symbol}")
        lines.append("    &[")
        for shell in shells:
            l = shell[0]
            prims = shell[1:]
            assert all(len(p) == 2 for p in prims), f"{pyscf_name} {symbol}: general contraction"
            exps = ", ".join(f(p[0]) for p in prims)
            coef = ", ".join(f(p[1]) for p in prims)
            lines.append(
                f"        ShellDef {{ l: {l}, exponents: &[{exps}], coefficients: &[{coef}] }},"
            )
        lines.append("    ],")
    lines.append("];")
    lines.append("")
    out = ROOT / "crates" / "dft-core" / "src" / "basis" / filename
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"wrote {out.relative_to(ROOT)}")


def write_sto3g() -> None:
    write_basis_table(
        "sto-3g",
        "STO3G",
        [
            "//! STO-3G contraction data for H-Ar.",
            "//!",
            "//! GENERATED by `scripts/gen_reference.py` from the STO-3G definition",
            "//! shipped with PySCF (Hehre, Stewart and Pople, J. Chem. Phys. 51, 2657",
            "//! (1969) and its second/third-row extensions). Do not edit by hand.",
            "//!",
            "//! Coefficients multiply *normalised* primitive Gaussians, which is the",
            "//! convention of the published tables; `Shell` applies that normalisation",
            "//! and then renormalises the contracted function.",
        ],
        "sto3g_data.rs",
    )


def write_631gs() -> None:
    # The citations are the ones in the header of PySCF's own data file
    # (pyscf/gto/basis/pople-basis/6-31Gs.dat, from the Basis Set Exchange).
    write_basis_table(
        "6-31g*",
        "B631GS",
        [
            "//! 6-31G* contraction data for H-Ar.",
            "//!",
            "//! GENERATED by `scripts/gen_reference.py` from the 6-31G* definition",
            "//! shipped with PySCF (Hariharan and Pople, Theor. Chim. Acta 28, 213",
            "//! (1973) for H-Ne; Francl et al., J. Chem. Phys. 77, 3654 (1982) for",
            "//! Na-Ar). Do not edit by hand.",
            "//!",
            "//! The d shells are the six-component Cartesian ones the basis was",
            "//! defined with, which is what the engine builds. H and He carry no",
            "//! polarisation functions (that would be 6-31G**).",
            "//!",
            "//! Coefficients multiply *normalised* primitive Gaussians, which is the",
            "//! convention of the published tables; `Shell` applies that normalisation",
            "//! and then renormalises the contracted function.",
        ],
        "b631gs_data.rs",
    )


# --------------------------------------------------------------------------
# Lebedev angular grids
# --------------------------------------------------------------------------


def write_lebedev() -> None:
    order_of = {n: deg for deg, n in gen_grid.LEBEDEV_ORDER.items()}
    lines = [
        "//! Lebedev-Laikov angular quadrature grids.",
        "//!",
        "//! GENERATED by `scripts/gen_reference.py` from the tables in PySCF/libcint",
        "//! (V. I. Lebedev and D. N. Laikov, Doklady Mathematics 59, 477 (1999)).",
        "//! Do not edit by hand.",
        "//!",
        "//! Points are unit vectors and weights sum to one, so a spherical average",
        "//! is `sum(w_i f(r_i))` and a surface integral is `4 pi` times that.",
        "",
        "/// One angular grid: unit vectors with weights summing to one.",
        "pub struct LebedevGrid {",
        "    /// Highest spherical-harmonic degree the grid integrates exactly.",
        "    pub degree: u32,",
        "    pub points: &'static [[f64; 3]],",
        "    pub weights: &'static [f64],",
        "}",
        "",
        "/// Available grids, ordered from coarsest to finest.",
        f"pub static GRIDS: [LebedevGrid; {len(LEBEDEV_POINTS)}] = [",
    ]
    for n in LEBEDEV_POINTS:
        grid = gen_grid.MakeAngularGrid(n)
        assert grid.shape == (n, 4), grid.shape
        assert abs(grid[:, 3].sum() - 1.0) < 1e-14
        pts = ",\n".join(
            f"            [{f(p[0])}, {f(p[1])}, {f(p[2])}]" for p in grid
        )
        wts = ",\n".join(f"            {f(w)}" for w in grid[:, 3])
        lines += [
            "    LebedevGrid {",
            f"        degree: {order_of[n]},",
            "        points: &[",
            pts + ",",
            "        ],",
            "        weights: &[",
            wts + ",",
            "        ],",
            "    },",
        ]
    lines += ["];", ""]
    out = ROOT / "crates" / "dft-core" / "src" / "grid" / "lebedev_data.rs"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"wrote {out.relative_to(ROOT)} ({sum(LEBEDEV_POINTS)} points)")


# --------------------------------------------------------------------------
# XC functional values
# --------------------------------------------------------------------------


def write_xc() -> None:
    """Pointwise Slater exchange + VWN5 correlation straight out of libxc."""
    rho = np.concatenate(
        [
            np.logspace(-10, 3, 40),  # spans the whole range a molecular grid sees
            np.array([1e-14, 0.5, 1.0, 2.0]),
        ]
    )
    rho = np.sort(rho)
    exc, vxc = dft.libxc.eval_xc("lda,vwn5", rho, spin=0)[:2]
    # libxc screens densities below ~1e-15 to exactly zero; the engine applies
    # its own cutoff there, so those points say nothing about the functional.
    unpolarized = [
        {"rho": float(r), "exc": float(e), "vrho": float(v)}
        for r, e, v in zip(rho, exc, vxc[0])
        if e != 0.0
    ]

    # Spin-polarised values matter from P4 onwards (UKS); pinning them down now
    # keeps the functional a solved problem when that phase starts.
    pairs = [
        (a, b)
        for a in np.logspace(-8, 1, 10)
        for b in (0.0, 1e-8, 1e-3, 0.1, 1.0)
    ]
    ra = np.array([p[0] for p in pairs])
    rb = np.array([p[1] for p in pairs])
    exc_p, vxc_p = dft.libxc.eval_xc("lda,vwn5", (ra, rb), spin=1)[:2]
    polarized = [
        {
            "rho_a": float(a),
            "rho_b": float(b),
            "exc": float(e),
            "vrho_a": float(va),
            "vrho_b": float(vb),
        }
        for a, b, e, va, vb in zip(ra, rb, exc_p, vxc_p[0][:, 0], vxc_p[0][:, 1])
        if e != 0.0
    ]

    dump(
        "xc_lda.json",
        {
            "functional": "LDA exchange (Slater) + VWN5 correlation",
            "source": "libxc via pyscf.dft.libxc.eval_xc('lda,vwn5')",
            "unpolarized": unpolarized,
            "polarized": polarized,
        },
    )


# --------------------------------------------------------------------------
# Integrals and SCF energies
# --------------------------------------------------------------------------

# Geometries in Angstrom. Experimental where available; exact numbers do not
# matter for a regression test as long as Rust and PySCF see the same ones.
GEOMETRIES = {
    "h2": [("H", (0.0, 0.0, 0.0)), ("H", (0.0, 0.0, 0.74))],
    "h2o": [
        ("O", (0.0, 0.0, 0.1173)),
        ("H", (0.0, 0.7572, -0.4693)),
        ("H", (0.0, -0.7572, -0.4693)),
    ],
    "ch4": [
        ("C", (0.0, 0.0, 0.0)),
        ("H", (0.6276, 0.6276, 0.6276)),
        ("H", (0.6276, -0.6276, -0.6276)),
        ("H", (-0.6276, 0.6276, -0.6276)),
        ("H", (-0.6276, -0.6276, 0.6276)),
    ],
    # Deliberately lopsided: no symmetry to hide an index mix-up behind.
    "h2o_distorted": [
        ("O", (0.03, -0.11, 0.17)),
        ("H", (0.21, 0.88, -0.31)),
        ("H", (-0.05, -0.62, -0.83)),
    ],
    # Third-row element: exercises the 3s/3p shells.
    "h2s": [
        ("S", (0.0, 0.0, 0.1030)),
        ("H", (0.0, 0.9617, -0.8240)),
        ("H", (0.0, -0.9617, -0.8240)),
    ],
    # Methane pulled off its tetrahedron, for the gradient reference: every
    # force component is non-zero and no symmetry can hide a wrong term.
    "ch4_distorted": [
        ("C", (0.04, -0.02, 0.03)),
        ("H", (0.78, 0.71, 0.55)),
        ("H", (0.55, -0.83, -0.71)),
        ("H", (-0.83, 0.62, -0.49)),
        ("H", (-0.61, -0.74, 0.97)),
    ],
    # Oxygen at a stretched bond, off-axis so all three components are alive.
    "o2_stretched": [
        ("O", (0.0, 0.0, 0.0)),
        ("O", (0.164, -0.090, 1.349)),
    ],
    # Linear, two heavy atoms.
    "co2": [
        ("C", (0.0, 0.0, 0.0)),
        ("O", (0.0, 0.0, 1.1621)),
        ("O", (0.0, 0.0, -1.1621)),
    ],
    # Open-shell systems, for the unrestricted path and the automatic spin
    # search. O2 is the one that matters: its ground state is a triplet, which
    # is exactly what the search has to discover on its own.
    "o2": [("O", (0.0, 0.0, 0.0)), ("O", (0.0, 0.0, 1.208))],
    # Planar methyl radical: an odd electron count, so a doublet with no choice
    # to make.
    "ch3": [
        ("C", (0.0, 0.0, 0.0)),
        ("H", (1.0790, 0.0, 0.0)),
        ("H", (-0.5395, 0.9344, 0.0)),
        ("H", (-0.5395, -0.9344, 0.0)),
    ],
    "oh": [("O", (0.0, 0.0, 0.0)), ("H", (0.0, 0.0, 0.9697))],
    "nh3": [
        ("N", (0.0, 0.0, 0.1173)),
        ("H", (0.0, 0.9377, -0.2737)),
        ("H", (0.8121, -0.4689, -0.2737)),
        ("H", (-0.8121, -0.4689, -0.2737)),
    ],
    "benzene": [
        ("C", (0.0000, 1.3970, 0.0)),
        ("C", (1.2098, 0.6985, 0.0)),
        ("C", (1.2098, -0.6985, 0.0)),
        ("C", (0.0000, -1.3970, 0.0)),
        ("C", (-1.2098, -0.6985, 0.0)),
        ("C", (-1.2098, 0.6985, 0.0)),
        ("H", (0.0000, 2.4810, 0.0)),
        ("H", (2.1486, 1.2405, 0.0)),
        ("H", (2.1486, -1.2405, 0.0)),
        ("H", (0.0000, -2.4810, 0.0)),
        ("H", (-2.1486, -1.2405, 0.0)),
        ("H", (-2.1486, 1.2405, 0.0)),
    ],
}


def make_mol(atoms, unit: str, basis: str, cart: bool, spin: int):
    """One neutral PySCF molecule, refusing a basis the engine would build differently.

    The engine builds every shell from Cartesian functions. For s and p shells
    that is the same thing as PySCF's default spherical ones, which is why the
    STO-3G references use `cart=False`; but a d shell has six Cartesian
    functions and five spherical ones, so a 6-31G* reference made without
    `cart=True` would be for a different basis (benzene: 102 functions
    against 96).
    """
    mol = gto.Mole()
    mol.atom = atoms
    mol.basis = basis
    mol.unit = unit
    mol.cart = cart
    mol.spin = spin
    mol.charge = 0
    mol.verbose = 0
    mol.build()
    assert cart or all(mol.bas_angular(i) < 2 for i in range(mol.nbas)), (
        f"{basis} has d shells and the engine's are Cartesian: pass cart=True"
    )
    return mol


def build_mol(name: str, basis: str = "sto-3g", cart: bool = False, spin: int = 0):
    atoms = [(sym, pos) for sym, pos in GEOMETRIES[name]]
    return make_mol(atoms, "Angstrom", basis, cart, spin)


def engine_normalisation(mol):
    """Factors taking PySCF's AO functions to the engine's.

    libcint normalises a Cartesian shell as a whole, so with `cart=True` the d
    functions do not have unit self-overlap (<xx|xx> = 3 <xy|xy>). The engine
    normalises every Cartesian function individually: engine function i is
    PySCF's times `scale[i]`. For s and p the factors are 1 to rounding.
    """
    return 1.0 / np.sqrt(np.diag(mol.intor("int1e_ovlp")))


def shell_defs(mol) -> list[dict]:
    """The shells in PySCF's own order, so the Rust side can assert it matches."""
    out = []
    for bas_id in range(mol.nbas):
        out.append(
            {
                "center": int(mol.bas_atom(bas_id)),
                "l": int(mol.bas_angular(bas_id)),
                "exponents": [float(x) for x in mol.bas_exp(bas_id)],
                # Published contraction coefficients, not the internally
                # renormalised ones libcint works with.
                "coefficients": [float(c) for c in mol.bas_ctr_coeff(bas_id)[:, 0]],
            }
        )
    return out


def sample_eri(eri, count: int) -> list[dict]:
    """A deterministic sample of (ij|kl) values, so the file stays small."""
    n = eri.shape[0]
    count = min(count, n**4)
    rng = random.Random(SEED)
    seen = set()
    out = []
    while len(out) < count:
        idx = tuple(rng.randrange(n) for _ in range(4))
        if idx in seen:
            continue
        seen.add(idx)
        i, j, k, l = idx
        out.append({"idx": list(idx), "value": float(eri[i, j, k, l])})
    return out


def integral_reference(key: str, name: str, basis: str, cart: bool, full_eri: bool):
    mol = build_mol(name, basis=basis, cart=cart)
    # Matrices over basis functions go into the engine's convention here, so the
    # Rust test compares element for element.
    scale = engine_normalisation(mol)

    def one(name_: str):
        return flat(mol.intor(name_) * scale[:, None] * scale[None, :])

    payload = {
        "molecule": name,
        "basis": basis,
        "cartesian": cart,
        "atoms": [
            {
                "z": int(mol.atom_charge(i)),
                # Bohr: the engine's own units, so the test does no conversion.
                "pos": [float(x) for x in mol.atom_coord(i)],
            }
            for i in range(mol.natm)
        ],
        "shells": shell_defs(mol),
        "ao_labels": [" ".join(lbl.split()) for lbl in mol.ao_labels()],
        "nbf": int(mol.nao),
        "nuclear_repulsion": float(mol.energy_nuc()),
        "normalization": [float(x) for x in scale],
        "overlap": one("int1e_ovlp"),
        "kinetic": one("int1e_kin"),
        "nuclear": one("int1e_nuc"),
    }
    eri = mol.intor("int2e", aosym="s1")
    eri = eri * scale[:, None, None, None] * scale[None, :, None, None]
    eri = eri * scale[None, None, :, None] * scale[None, None, None, :]
    if full_eri:
        payload["eri_full"] = flat(eri)
    payload["eri_samples"] = sample_eri(eri, 300)
    dump(f"integrals_{key}.json", payload)


def scf_reference(
    key: str, name: str, with_density: bool = True, basis: str = "sto-3g", cart: bool = False
):
    mol = build_mol(name, basis=basis, cart=cart)
    mf = dft.RKS(mol)
    mf.xc = "lda,vwn5"
    mf.grids.level = REFERENCE_GRID_LEVEL
    mf.conv_tol = 1e-11
    energy = float(mf.kernel())
    assert mf.converged, f"{name} did not converge"

    dm = mf.make_rdm1()
    if cart:
        # The density's coefficients go the opposite way to a matrix of
        # integrals, so that the energy (a trace of the two) stays the same.
        # Spherical s and p functions are left alone: their factors are 1 to
        # rounding, and applying them would move the STO-3G files by an ulp.
        scale = engine_normalisation(mol)
        dm = dm / scale[:, None] / scale[None, :]
    payload = {
        "molecule": name,
        "basis": basis,
        "functional": "lda,vwn5",
        # Bohr, so the Rust test rebuilds exactly this geometry.
        "atoms": [
            {
                "z": int(mol.atom_charge(i)),
                "pos": [float(x) for x in mol.atom_coord(i)],
            }
            for i in range(mol.natm)
        ],
        "grid_level": REFERENCE_GRID_LEVEL,
        "n_electrons": int(mol.nelectron),
        "nbf": int(mol.nao),
        "nuclear_repulsion": float(mol.energy_nuc()),
        "energy": energy,
        # Per-term breakdown at the converged density, so a Rust failure says
        # which term is wrong instead of only that the total is off.
        "e_core": float(mf.scf_summary["e1"]),
        "e_coulomb": float(mf.scf_summary["coul"]),
        "e_xc": float(mf.scf_summary["exc"]),
        "mo_energies": [float(x) for x in mf.mo_energy],
        "homo": float(mf.mo_energy[mol.nelectron // 2 - 1]),
    }
    if with_density:
        # The Rust test evaluates its energy expression on *this* density matrix,
        # which separates the energy functional from SCF convergence.
        payload["density_matrix"] = flat(dm)
    # How much of the total is quadrature: the coarse-grid number bounds what a
    # Rust grid of modest size can be expected to reproduce.
    coarse = dft.RKS(mol)
    coarse.xc = "lda,vwn5"
    coarse.grids.level = 3
    coarse.conv_tol = 1e-11
    payload["energy_grid_level_3"] = float(coarse.kernel())
    dump(f"scf_{key}.json", payload)


def atomic_reference(filename: str = "scf_atoms.json", basis: str = "sto-3g", cart: bool = False):
    """Closed-shell atoms: a spherical atomic solver must reproduce these exactly."""
    out = []
    for symbol in ("He", "Be", "Ne", "Mg", "Ar"):
        mol = make_mol([(symbol, (0.0, 0.0, 0.0))], "Angstrom", basis, cart, 0)
        mf = dft.RKS(mol)
        mf.xc = "lda,vwn5"
        mf.grids.level = REFERENCE_GRID_LEVEL
        mf.conv_tol = 1e-11
        energy = float(mf.kernel())
        assert mf.converged
        out.append(
            {
                "symbol": symbol,
                "z": int(mol.atom_charge(0)),
                "n_electrons": int(mol.nelectron),
                "nbf": int(mol.nao),
                "energy": energy,
            }
        )
    dump(filename, {"functional": "lda,vwn5", "basis": basis, "atoms": out})


# --------------------------------------------------------------------------
# Open-shell (unrestricted) references
# --------------------------------------------------------------------------

# Spin multiplicity of each open-shell reference, 2S+1. O2 carries the whole
# point of the automatic search: its ground state is the triplet, and nothing in
# the geometry says so.
OPEN_SHELL_MOLECULES = [
    ("o2_triplet", "o2", 3),
    ("o2_singlet", "o2", 1),
    ("ch3_doublet", "ch3", 2),
    ("oh_doublet", "oh", 2),
]

# Atoms, where the unrestricted solution differs most from the restricted one.
# Nitrogen is a quartet: three unpaired electrons exercise a multiplicity the
# molecular cases never reach. Aluminium and silicon are the hard ones - their
# 3s and 3p levels are close enough that an ordinary SCF oscillates between the
# equivalent ways of occupying the shell, and the engine needs a level shift to
# reach the answer PySCF reaches with its second-order solver.
OPEN_SHELL_ATOMS = [("H", 2), ("C", 3), ("N", 4), ("O", 3), ("Al", 2), ("Si", 3)]


def unrestricted_payload(mol, label: str) -> dict:
    """Converges one system with UKS (or RKS when it is closed-shell) and
    records everything a Rust test needs to localise a disagreement."""
    restricted = mol.spin == 0
    mf = dft.RKS(mol) if restricted else dft.UKS(mol)
    mf.xc = "lda,vwn5"
    mf.grids.level = REFERENCE_GRID_LEVEL
    mf.conv_tol = 1e-11
    energy = float(mf.kernel())
    if not mf.converged:
        # An open-shell atom has a partly filled, exactly degenerate p shell, and
        # ordinary DIIS oscillates between the equivalent ways of occupying it.
        # The second-order solver walks down to the stationary point instead of
        # rediagonalising, so the degeneracy costs it nothing.
        mf = mf.newton()
        energy = float(mf.kernel())
    assert mf.converged, f"{label} did not converge"

    dm = mf.make_rdm1()
    mo_energy = mf.mo_energy
    if restricted:
        # Written in the same shape as the open-shell case so the Rust side has
        # one code path: a closed shell is the special case where the two spin
        # channels are identical.
        dm = np.array([dm * 0.5, dm * 0.5])
        mo_energy = np.array([mo_energy, mo_energy])

    n_alpha, n_beta = mol.nelec
    payload = {
        "key": label,
        "charge": int(mol.charge),
        "multiplicity": int(mol.spin) + 1,
        "n_alpha": int(n_alpha),
        "n_beta": int(n_beta),
        "unrestricted": not restricted,
        "atoms": [
            {
                "z": int(mol.atom_charge(i)),
                "pos": [float(x) for x in mol.atom_coord(i)],
            }
            for i in range(mol.natm)
        ],
        "nbf": int(mol.nao),
        "n_electrons": int(mol.nelectron),
        "nuclear_repulsion": float(mol.energy_nuc()),
        "energy": energy,
        "e_core": float(mf.scf_summary["e1"]),
        "e_coulomb": float(mf.scf_summary["coul"]),
        "e_xc": float(mf.scf_summary["exc"]),
        # Per spin channel, alpha first.
        "mo_energies": [[float(x) for x in row] for row in mo_energy],
        "density_matrix": [flat(block) for block in dm],
        # <S^2>, which says how far the unrestricted solution is from a spin
        # eigenstate. The engine computes it the same way and must agree.
        "spin_squared": float(mf.spin_square()[0]) if not restricted else 0.0,
    }
    coarse = dft.RKS(mol) if restricted else dft.UKS(mol)
    coarse.xc = "lda,vwn5"
    coarse.grids.level = 3
    coarse.conv_tol = 1e-11
    payload["energy_grid_level_3"] = float(coarse.kernel())
    return payload


def open_shell_reference() -> None:
    systems = []
    for key, name, multiplicity in OPEN_SHELL_MOLECULES:
        mol = build_mol(name, spin=multiplicity - 1)
        systems.append(unrestricted_payload(mol, key))

    atoms = []
    for symbol, multiplicity in OPEN_SHELL_ATOMS:
        mol = gto.Mole()
        mol.atom = [(symbol, (0.0, 0.0, 0.0))]
        mol.basis = "sto-3g"
        mol.spin = multiplicity - 1
        mol.verbose = 0
        mol.build()
        atoms.append(unrestricted_payload(mol, f"{symbol.lower()}_atom"))

    dump(
        "scf_open_shell.json",
        {
            "functional": "lda,vwn5",
            "basis": "sto-3g",
            "grid_level": REFERENCE_GRID_LEVEL,
            "systems": systems,
            "atoms": atoms,
        },
    )


# --------------------------------------------------------------------------
# Analytic nuclear gradients, and a relaxed geometry to compare against
# --------------------------------------------------------------------------

# Geometries the Rust gradient tests check, with the spin multiplicity each is
# solved at. The distorted ones carry large forces, which is the point: a term
# that is wrong by a few percent shows up as a few percent of something big.
GRADIENT_CASES = [
    ("h2o_distorted", "h2o_distorted", 1),
    ("ch4_distorted", "ch4_distorted", 1),
    ("o2_stretched_triplet", "o2_stretched", 3),
    ("ch3_doublet", "ch3", 2),
]


def _mean_field(mol):
    """A converged SVWN5 calculation, restricted or not as the spin requires."""
    mf = dft.RKS(mol) if mol.spin == 0 else dft.UKS(mol)
    mf.xc = "lda,vwn5"
    mf.grids.level = REFERENCE_GRID_LEVEL
    mf.conv_tol = 1e-12
    energy = float(mf.kernel())
    if not mf.converged:
        mf = mf.newton()
        energy = float(mf.kernel())
    assert mf.converged
    return mf, energy


def _analytic_gradient(mf):
    """dE/dR in Hartree/Bohr, with the grid held still.

    `grid_response = False` is PySCF's default and is the same approximation the
    engine makes: the derivatives of the Becke weights are left out. Turning it
    on here would compare two different quantities.
    """
    grad = mf.nuc_grad_method()
    grad.grid_response = False
    return grad.kernel()


def gradient_reference(
    filename: str, basis: str, cart: bool, relaxed: list[tuple[str, int]]
) -> None:
    cases = []
    for key, name, multiplicity in GRADIENT_CASES:
        mol = build_mol(name, basis=basis, cart=cart, spin=multiplicity - 1)
        mf, energy = _mean_field(mol)
        gradient = _analytic_gradient(mf)
        cases.append(
            {
                "key": key,
                "multiplicity": multiplicity,
                "atoms": [
                    {
                        "z": int(mol.atom_charge(i)),
                        "pos": [float(x) for x in mol.atom_coord(i)],
                    }
                    for i in range(mol.natm)
                ],
                "energy": energy,
                # Hartree/Bohr, [natm][3].
                "gradient": [[float(x) for x in row] for row in gradient],
            }
        )

    dump(
        filename,
        {
            "functional": "lda,vwn5",
            "basis": basis,
            "grid_level": REFERENCE_GRID_LEVEL,
            "grid_response": False,
            "source": "pyscf mf.nuc_grad_method().kernel()",
            "cases": cases,
            "relaxed": [
                relaxed_geometry(name, multiplicity, basis, cart)
                for name, multiplicity in relaxed
            ],
        },
    )


def relaxed_geometry(name: str, multiplicity: int, basis: str, cart: bool) -> dict:
    """Minimises the energy with scipy's BFGS over PySCF energies and gradients.

    Deliberately not PySCF's own geometry optimiser: an independent optimiser
    over an independent engine is the better reference - if the Rust optimiser
    lands on the same structure, two different minimisers agreed about where the
    minimum is.
    """
    from scipy.optimize import minimize

    template = GEOMETRIES[name]
    symbols = [symbol for symbol, _ in template]

    def build(flat_bohr):
        atoms = [
            (symbol, tuple(flat_bohr[3 * i : 3 * i + 3]))
            for i, symbol in enumerate(symbols)
        ]
        return make_mol(atoms, "Bohr", basis, cart, multiplicity - 1)

    def objective(flat_bohr):
        mf, energy = _mean_field(build(flat_bohr))
        return energy, _analytic_gradient(mf).ravel()

    start = build_mol(name, spin=multiplicity - 1).atom_coords().ravel()
    outcome = minimize(objective, start, jac=True, method="BFGS", tol=1e-8,
                       options={"gtol": 1e-6, "maxiter": 200})
    assert outcome.success, f"{name} did not relax: {outcome.message}"

    coords = np.asarray(outcome.x).reshape(-1, 3)

    def distance(i, j):
        return float(np.linalg.norm(coords[i] - coords[j]))

    def angle(i, j, k):
        u = coords[i] - coords[j]
        v = coords[k] - coords[j]
        cosine = float(u @ v / (np.linalg.norm(u) * np.linalg.norm(v)))
        return float(np.degrees(np.arccos(np.clip(cosine, -1.0, 1.0))))

    # Every bond from the first atom, which is the heavy one in both cases here,
    # plus one angle across it. Enough to pin the structure without writing out
    # coordinates that depend on an arbitrary orientation.
    bonds = [distance(0, i) for i in range(1, len(symbols))]
    return {
        "key": name,
        "multiplicity": multiplicity,
        "symbols": symbols,
        "start": [float(x) for x in start],
        "energy": float(outcome.fun),
        "max_force": float(np.abs(outcome.jac).max()),
        # Bohr.
        "coords": [float(x) for x in np.asarray(outcome.x)],
        "bonds_from_first_atom": bonds,
        "angle_1_0_2": angle(1, 0, 2),
    }


def flat(matrix) -> list[float]:
    return [float(x) for x in np.asarray(matrix).ravel()]


def dump(filename: str, payload: dict) -> None:
    DATA.mkdir(parents=True, exist_ok=True)
    path = DATA / filename
    path.write_text(json.dumps(payload, indent=1, sort_keys=True) + "\n")
    print(f"wrote {path.relative_to(ROOT)} ({path.stat().st_size / 1024:.0f} kB)")


def main() -> None:
    write_units()
    write_sto3g()
    write_631gs()
    write_lebedev()
    write_xc()

    integral_reference("h2_sto3g", "h2", "sto-3g", cart=False, full_eri=True)
    integral_reference("h2o_sto3g", "h2o_distorted", "sto-3g", cart=False, full_eri=True)
    integral_reference("h2s_sto3g", "h2s", "sto-3g", cart=False, full_eri=False)
    integral_reference("co2_sto3g", "co2", "sto-3g", cart=False, full_eri=False)
    # The integral tests check the l = 2 path against this one, and
    # `b631gs_table_matches_reference` checks the engine's 6-31G* table against
    # the shells PySCF used for it.
    integral_reference("h2o_631gs", "h2o_distorted", "6-31G*", cart=True, full_eri=False)

    for key, name in [
        ("h2", "h2"),
        ("h2o", "h2o"),
        ("ch4", "ch4"),
        ("nh3", "nh3"),
        ("h2s", "h2s"),
        ("co2", "co2"),
    ]:
        scf_reference(key, name)
    scf_reference("benzene", "benzene", with_density=False)
    atomic_reference()
    open_shell_reference()
    gradient_reference("gradients.json", "sto-3g", False, [("h2o", 1), ("ch4", 1)])

    # 6-31G*, the basis of the "measure the shape" level. Benzene is left out:
    # one 6-31G* SCF of it takes the engine about 10 s and the tests solve each
    # file several times, while water, methane and ammonia already put the d
    # shell on three different first-row atoms (the atoms add Mg and Ar).
    for name in ("h2o", "ch4", "nh3"):
        scf_reference(f"{name}_631gs", name, basis="6-31G*", cart=True)
    atomic_reference("scf_atoms_631gs.json", "6-31G*", cart=True)
    gradient_reference("gradients_631gs.json", "6-31G*", True, [("h2o", 1)])


if __name__ == "__main__":
    main()
