#!/usr/bin/env python3
"""Generates the basis/grid tables and the reference values the Rust tests check against.

Nothing in `dft-core` may contain numbers typed from memory: every table and
every expected value either comes out of this script or is derived
independently inside the test itself.

Outputs:
  crates/dft-core/src/basis/sto3g_data.rs    STO-3G contractions for H-Ar
  crates/dft-core/src/grid/lebedev_data.rs   Lebedev-Laikov angular grids
  crates/dft-core/tests/data/*.json          reference integrals, XC values, energies

Usage:
  python3 -m venv .venv && .venv/bin/pip install pyscf
  .venv/bin/python scripts/gen_reference.py
"""

from __future__ import annotations

import json
import random
from pathlib import Path

import numpy as np
from pyscf import dft, gto
from pyscf.data.elements import ELEMENTS
from pyscf.dft import gen_grid

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "crates" / "dft-core" / "tests" / "data"

# Angular grid orders the engine embeds; the pruning scheme picks among these.
LEBEDEV_POINTS = [26, 50, 110, 194, 302]

# A dense grid makes the DFT reference energies essentially grid-converged, so a
# disagreement in the Rust tests points at the functional or the integrals
# rather than at quadrature noise.
REFERENCE_GRID_LEVEL = 9

SEED = 20260918


def f(x: float) -> str:
    """Round-trippable float literal."""
    return repr(float(x))


# --------------------------------------------------------------------------
# STO-3G table
# --------------------------------------------------------------------------


def write_sto3g() -> None:
    lines = [
        "//! STO-3G contraction data for H-Ar.",
        "//!",
        "//! GENERATED by `scripts/gen_reference.py` from the STO-3G definition",
        "//! shipped with PySCF (Hehre, Stewart and Pople, J. Chem. Phys. 51, 2657",
        "//! (1969) and its second/third-row extensions). Do not edit by hand.",
        "//!",
        "//! Coefficients multiply *normalised* primitive Gaussians, which is the",
        "//! convention of the published tables; `Shell` applies that normalisation",
        "//! and then renormalises the contracted function.",
        "",
        "use super::ShellDef;",
        "",
        "/// Shell definitions for each element, indexed by `z - 1`.",
        "pub static STO3G: [&[ShellDef]; 18] = [",
    ]
    for z in range(1, 19):
        symbol = ELEMENTS[z]
        shells = gto.basis.load("sto-3g", symbol)
        lines.append(f"    // {symbol}")
        lines.append("    &[")
        for shell in shells:
            l = shell[0]
            prims = shell[1:]
            exps = ", ".join(f(p[0]) for p in prims)
            coef = ", ".join(f(p[1]) for p in prims)
            lines.append(
                f"        ShellDef {{ l: {l}, exponents: &[{exps}], coefficients: &[{coef}] }},"
            )
        lines.append("    ],")
    lines.append("];")
    lines.append("")
    out = ROOT / "crates" / "dft-core" / "src" / "basis" / "sto3g_data.rs"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"wrote {out.relative_to(ROOT)}")


# --------------------------------------------------------------------------
# Lebedev angular grids
# --------------------------------------------------------------------------


def write_lebedev() -> None:
    order_of = {n: deg for deg, n in gen_grid.LEBEDEV_ORDER.items()}
    lines = [
        "//! Lebedev-Laikov angular quadrature grids.",
        "//!",
        "//! GENERATED by `scripts/gen_reference.py` from the tables in PySCF/libcint",
        "//! (V. I. Lebedev and D. N. Laikov, Doklady Mathematics 59, 477 (1999)).",
        "//! Do not edit by hand.",
        "//!",
        "//! Points are unit vectors and weights sum to one, so a spherical average",
        "//! is `sum(w_i f(r_i))` and a surface integral is `4 pi` times that.",
        "",
        "/// One angular grid: unit vectors with weights summing to one.",
        "pub struct LebedevGrid {",
        "    /// Highest spherical-harmonic degree the grid integrates exactly.",
        "    pub degree: u32,",
        "    pub points: &'static [[f64; 3]],",
        "    pub weights: &'static [f64],",
        "}",
        "",
        "/// Available grids, ordered from coarsest to finest.",
        f"pub static GRIDS: [LebedevGrid; {len(LEBEDEV_POINTS)}] = [",
    ]
    for n in LEBEDEV_POINTS:
        grid = gen_grid.MakeAngularGrid(n)
        assert grid.shape == (n, 4), grid.shape
        assert abs(grid[:, 3].sum() - 1.0) < 1e-14
        pts = ",\n".join(
            f"            [{f(p[0])}, {f(p[1])}, {f(p[2])}]" for p in grid
        )
        wts = ",\n".join(f"            {f(w)}" for w in grid[:, 3])
        lines += [
            "    LebedevGrid {",
            f"        degree: {order_of[n]},",
            "        points: &[",
            pts + ",",
            "        ],",
            "        weights: &[",
            wts + ",",
            "        ],",
            "    },",
        ]
    lines += ["];", ""]
    out = ROOT / "crates" / "dft-core" / "src" / "grid" / "lebedev_data.rs"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"wrote {out.relative_to(ROOT)} ({sum(LEBEDEV_POINTS)} points)")


# --------------------------------------------------------------------------
# XC functional values
# --------------------------------------------------------------------------


def write_xc() -> None:
    """Pointwise Slater exchange + VWN5 correlation straight out of libxc."""
    rho = np.concatenate(
        [
            np.logspace(-10, 3, 40),  # spans the whole range a molecular grid sees
            np.array([1e-14, 0.5, 1.0, 2.0]),
        ]
    )
    rho = np.sort(rho)
    exc, vxc = dft.libxc.eval_xc("lda,vwn5", rho, spin=0)[:2]
    # libxc screens densities below ~1e-15 to exactly zero; the engine applies
    # its own cutoff there, so those points say nothing about the functional.
    unpolarized = [
        {"rho": float(r), "exc": float(e), "vrho": float(v)}
        for r, e, v in zip(rho, exc, vxc[0])
        if e != 0.0
    ]

    # Spin-polarised values matter from P4 onwards (UKS); pinning them down now
    # keeps the functional a solved problem when that phase starts.
    pairs = [
        (a, b)
        for a in np.logspace(-8, 1, 10)
        for b in (0.0, 1e-8, 1e-3, 0.1, 1.0)
    ]
    ra = np.array([p[0] for p in pairs])
    rb = np.array([p[1] for p in pairs])
    exc_p, vxc_p = dft.libxc.eval_xc("lda,vwn5", (ra, rb), spin=1)[:2]
    polarized = [
        {
            "rho_a": float(a),
            "rho_b": float(b),
            "exc": float(e),
            "vrho_a": float(va),
            "vrho_b": float(vb),
        }
        for a, b, e, va, vb in zip(ra, rb, exc_p, vxc_p[0][:, 0], vxc_p[0][:, 1])
        if e != 0.0
    ]

    dump(
        "xc_lda.json",
        {
            "functional": "LDA exchange (Slater) + VWN5 correlation",
            "source": "libxc via pyscf.dft.libxc.eval_xc('lda,vwn5')",
            "unpolarized": unpolarized,
            "polarized": polarized,
        },
    )


# --------------------------------------------------------------------------
# Integrals and SCF energies
# --------------------------------------------------------------------------

# Geometries in Angstrom. Experimental where available; exact numbers do not
# matter for a regression test as long as Rust and PySCF see the same ones.
GEOMETRIES = {
    "h2": [("H", (0.0, 0.0, 0.0)), ("H", (0.0, 0.0, 0.74))],
    "h2o": [
        ("O", (0.0, 0.0, 0.1173)),
        ("H", (0.0, 0.7572, -0.4693)),
        ("H", (0.0, -0.7572, -0.4693)),
    ],
    "ch4": [
        ("C", (0.0, 0.0, 0.0)),
        ("H", (0.6276, 0.6276, 0.6276)),
        ("H", (0.6276, -0.6276, -0.6276)),
        ("H", (-0.6276, 0.6276, -0.6276)),
        ("H", (-0.6276, -0.6276, 0.6276)),
    ],
    # Deliberately lopsided: no symmetry to hide an index mix-up behind.
    "h2o_distorted": [
        ("O", (0.03, -0.11, 0.17)),
        ("H", (0.21, 0.88, -0.31)),
        ("H", (-0.05, -0.62, -0.83)),
    ],
    # Third-row element: exercises the 3s/3p shells.
    "h2s": [
        ("S", (0.0, 0.0, 0.1030)),
        ("H", (0.0, 0.9617, -0.8240)),
        ("H", (0.0, -0.9617, -0.8240)),
    ],
    # Linear, two heavy atoms.
    "co2": [
        ("C", (0.0, 0.0, 0.0)),
        ("O", (0.0, 0.0, 1.1621)),
        ("O", (0.0, 0.0, -1.1621)),
    ],
    # Open-shell systems, for the unrestricted path and the automatic spin
    # search. O2 is the one that matters: its ground state is a triplet, which
    # is exactly what the search has to discover on its own.
    "o2": [("O", (0.0, 0.0, 0.0)), ("O", (0.0, 0.0, 1.208))],
    # Planar methyl radical: an odd electron count, so a doublet with no choice
    # to make.
    "ch3": [
        ("C", (0.0, 0.0, 0.0)),
        ("H", (1.0790, 0.0, 0.0)),
        ("H", (-0.5395, 0.9344, 0.0)),
        ("H", (-0.5395, -0.9344, 0.0)),
    ],
    "oh": [("O", (0.0, 0.0, 0.0)), ("H", (0.0, 0.0, 0.9697))],
    "nh3": [
        ("N", (0.0, 0.0, 0.1173)),
        ("H", (0.0, 0.9377, -0.2737)),
        ("H", (0.8121, -0.4689, -0.2737)),
        ("H", (-0.8121, -0.4689, -0.2737)),
    ],
    "benzene": [
        ("C", (0.0000, 1.3970, 0.0)),
        ("C", (1.2098, 0.6985, 0.0)),
        ("C", (1.2098, -0.6985, 0.0)),
        ("C", (0.0000, -1.3970, 0.0)),
        ("C", (-1.2098, -0.6985, 0.0)),
        ("C", (-1.2098, 0.6985, 0.0)),
        ("H", (0.0000, 2.4810, 0.0)),
        ("H", (2.1486, 1.2405, 0.0)),
        ("H", (2.1486, -1.2405, 0.0)),
        ("H", (0.0000, -2.4810, 0.0)),
        ("H", (-2.1486, -1.2405, 0.0)),
        ("H", (-2.1486, 1.2405, 0.0)),
    ],
}


def build_mol(name: str, basis: str = "sto-3g", cart: bool = False, spin: int = 0):
    mol = gto.Mole()
    mol.atom = [(sym, pos) for sym, pos in GEOMETRIES[name]]
    mol.basis = basis
    mol.unit = "Angstrom"
    mol.cart = cart
    mol.spin = spin
    mol.charge = 0
    mol.verbose = 0
    mol.build()
    return mol


def shell_defs(mol) -> list[dict]:
    """The shells in PySCF's own order, so the Rust side can assert it matches."""
    out = []
    for bas_id in range(mol.nbas):
        out.append(
            {
                "center": int(mol.bas_atom(bas_id)),
                "l": int(mol.bas_angular(bas_id)),
                "exponents": [float(x) for x in mol.bas_exp(bas_id)],
                # Published contraction coefficients, not the internally
                # renormalised ones libcint works with.
                "coefficients": [float(c) for c in mol.bas_ctr_coeff(bas_id)[:, 0]],
            }
        )
    return out


def sample_eri(eri, count: int) -> list[dict]:
    """A deterministic sample of (ij|kl) values, so the file stays small."""
    n = eri.shape[0]
    count = min(count, n**4)
    rng = random.Random(SEED)
    seen = set()
    out = []
    while len(out) < count:
        idx = tuple(rng.randrange(n) for _ in range(4))
        if idx in seen:
            continue
        seen.add(idx)
        i, j, k, l = idx
        out.append({"idx": list(idx), "value": float(eri[i, j, k, l])})
    return out


def integral_reference(key: str, name: str, basis: str, cart: bool, full_eri: bool):
    mol = build_mol(name, basis=basis, cart=cart)
    # libcint normalises a Cartesian shell as a whole, so with `cart=True` the
    # d functions do not have unit self-overlap (<xx|xx> = 3 <xy|xy>). The engine
    # normalises every Cartesian function individually, so scale the reference
    # matrices into that convention here; for s and p the factors are all 1.
    scale = 1.0 / np.sqrt(np.diag(mol.intor("int1e_ovlp")))

    def one(name_: str):
        return flat(mol.intor(name_) * scale[:, None] * scale[None, :])

    payload = {
        "molecule": name,
        "basis": basis,
        "cartesian": cart,
        "atoms": [
            {
                "z": int(mol.atom_charge(i)),
                # Bohr: the engine's own units, so the test does no conversion.
                "pos": [float(x) for x in mol.atom_coord(i)],
            }
            for i in range(mol.natm)
        ],
        "shells": shell_defs(mol),
        "ao_labels": [" ".join(lbl.split()) for lbl in mol.ao_labels()],
        "nbf": int(mol.nao),
        "nuclear_repulsion": float(mol.energy_nuc()),
        "normalization": [float(x) for x in scale],
        "overlap": one("int1e_ovlp"),
        "kinetic": one("int1e_kin"),
        "nuclear": one("int1e_nuc"),
    }
    eri = mol.intor("int2e", aosym="s1")
    eri = eri * scale[:, None, None, None] * scale[None, :, None, None]
    eri = eri * scale[None, None, :, None] * scale[None, None, None, :]
    if full_eri:
        payload["eri_full"] = flat(eri)
    payload["eri_samples"] = sample_eri(eri, 300)
    dump(f"integrals_{key}.json", payload)


def scf_reference(key: str, name: str, with_density: bool = True):
    mol = build_mol(name)
    mf = dft.RKS(mol)
    mf.xc = "lda,vwn5"
    mf.grids.level = REFERENCE_GRID_LEVEL
    mf.conv_tol = 1e-11
    energy = float(mf.kernel())
    assert mf.converged, f"{name} did not converge"

    dm = mf.make_rdm1()
    payload = {
        "molecule": name,
        "basis": "sto-3g",
        "functional": "lda,vwn5",
        # Bohr, so the Rust test rebuilds exactly this geometry.
        "atoms": [
            {
                "z": int(mol.atom_charge(i)),
                "pos": [float(x) for x in mol.atom_coord(i)],
            }
            for i in range(mol.natm)
        ],
        "grid_level": REFERENCE_GRID_LEVEL,
        "n_electrons": int(mol.nelectron),
        "nbf": int(mol.nao),
        "nuclear_repulsion": float(mol.energy_nuc()),
        "energy": energy,
        # Per-term breakdown at the converged density, so a Rust failure says
        # which term is wrong instead of only that the total is off.
        "e_core": float(mf.scf_summary["e1"]),
        "e_coulomb": float(mf.scf_summary["coul"]),
        "e_xc": float(mf.scf_summary["exc"]),
        "mo_energies": [float(x) for x in mf.mo_energy],
        "homo": float(mf.mo_energy[mol.nelectron // 2 - 1]),
    }
    if with_density:
        # The Rust test evaluates its energy expression on *this* density matrix,
        # which separates the energy functional from SCF convergence.
        payload["density_matrix"] = flat(dm)
    # How much of the total is quadrature: the coarse-grid number bounds what a
    # Rust grid of modest size can be expected to reproduce.
    coarse = dft.RKS(mol)
    coarse.xc = "lda,vwn5"
    coarse.grids.level = 3
    coarse.conv_tol = 1e-11
    payload["energy_grid_level_3"] = float(coarse.kernel())
    dump(f"scf_{key}.json", payload)


def atomic_reference():
    """Closed-shell atoms: a spherical atomic solver must reproduce these exactly."""
    out = []
    for symbol in ("He", "Be", "Ne", "Mg", "Ar"):
        mol = gto.Mole()
        mol.atom = [(symbol, (0.0, 0.0, 0.0))]
        mol.basis = "sto-3g"
        mol.spin = 0
        mol.verbose = 0
        mol.build()
        mf = dft.RKS(mol)
        mf.xc = "lda,vwn5"
        mf.grids.level = REFERENCE_GRID_LEVEL
        mf.conv_tol = 1e-11
        energy = float(mf.kernel())
        assert mf.converged
        out.append(
            {
                "symbol": symbol,
                "z": int(mol.atom_charge(0)),
                "n_electrons": int(mol.nelectron),
                "nbf": int(mol.nao),
                "energy": energy,
            }
        )
    dump("scf_atoms.json", {"functional": "lda,vwn5", "basis": "sto-3g", "atoms": out})


# --------------------------------------------------------------------------
# Open-shell (unrestricted) references
# --------------------------------------------------------------------------

# Spin multiplicity of each open-shell reference, 2S+1. O2 carries the whole
# point of the automatic search: its ground state is the triplet, and nothing in
# the geometry says so.
OPEN_SHELL_MOLECULES = [
    ("o2_triplet", "o2", 3),
    ("o2_singlet", "o2", 1),
    ("ch3_doublet", "ch3", 2),
    ("oh_doublet", "oh", 2),
]

# Atoms, where the unrestricted solution differs most from the restricted one.
# Nitrogen is a quartet: three unpaired electrons exercise a multiplicity the
# molecular cases never reach. Aluminium and silicon are the hard ones - their
# 3s and 3p levels are close enough that an ordinary SCF oscillates between the
# equivalent ways of occupying the shell, and the engine needs a level shift to
# reach the answer PySCF reaches with its second-order solver.
OPEN_SHELL_ATOMS = [("H", 2), ("C", 3), ("N", 4), ("O", 3), ("Al", 2), ("Si", 3)]


def unrestricted_payload(mol, label: str) -> dict:
    """Converges one system with UKS (or RKS when it is closed-shell) and
    records everything a Rust test needs to localise a disagreement."""
    restricted = mol.spin == 0
    mf = dft.RKS(mol) if restricted else dft.UKS(mol)
    mf.xc = "lda,vwn5"
    mf.grids.level = REFERENCE_GRID_LEVEL
    mf.conv_tol = 1e-11
    energy = float(mf.kernel())
    if not mf.converged:
        # An open-shell atom has a partly filled, exactly degenerate p shell, and
        # ordinary DIIS oscillates between the equivalent ways of occupying it.
        # The second-order solver walks down to the stationary point instead of
        # rediagonalising, so the degeneracy costs it nothing.
        mf = mf.newton()
        energy = float(mf.kernel())
    assert mf.converged, f"{label} did not converge"

    dm = mf.make_rdm1()
    mo_energy = mf.mo_energy
    if restricted:
        # Written in the same shape as the open-shell case so the Rust side has
        # one code path: a closed shell is the special case where the two spin
        # channels are identical.
        dm = np.array([dm * 0.5, dm * 0.5])
        mo_energy = np.array([mo_energy, mo_energy])

    n_alpha, n_beta = mol.nelec
    payload = {
        "key": label,
        "charge": int(mol.charge),
        "multiplicity": int(mol.spin) + 1,
        "n_alpha": int(n_alpha),
        "n_beta": int(n_beta),
        "unrestricted": not restricted,
        "atoms": [
            {
                "z": int(mol.atom_charge(i)),
                "pos": [float(x) for x in mol.atom_coord(i)],
            }
            for i in range(mol.natm)
        ],
        "nbf": int(mol.nao),
        "n_electrons": int(mol.nelectron),
        "nuclear_repulsion": float(mol.energy_nuc()),
        "energy": energy,
        "e_core": float(mf.scf_summary["e1"]),
        "e_coulomb": float(mf.scf_summary["coul"]),
        "e_xc": float(mf.scf_summary["exc"]),
        # Per spin channel, alpha first.
        "mo_energies": [[float(x) for x in row] for row in mo_energy],
        "density_matrix": [flat(block) for block in dm],
        # <S^2>, which says how far the unrestricted solution is from a spin
        # eigenstate. The engine computes it the same way and must agree.
        "spin_squared": float(mf.spin_square()[0]) if not restricted else 0.0,
    }
    coarse = dft.RKS(mol) if restricted else dft.UKS(mol)
    coarse.xc = "lda,vwn5"
    coarse.grids.level = 3
    coarse.conv_tol = 1e-11
    payload["energy_grid_level_3"] = float(coarse.kernel())
    return payload


def open_shell_reference() -> None:
    systems = []
    for key, name, multiplicity in OPEN_SHELL_MOLECULES:
        mol = build_mol(name, spin=multiplicity - 1)
        systems.append(unrestricted_payload(mol, key))

    atoms = []
    for symbol, multiplicity in OPEN_SHELL_ATOMS:
        mol = gto.Mole()
        mol.atom = [(symbol, (0.0, 0.0, 0.0))]
        mol.basis = "sto-3g"
        mol.spin = multiplicity - 1
        mol.verbose = 0
        mol.build()
        atoms.append(unrestricted_payload(mol, f"{symbol.lower()}_atom"))

    dump(
        "scf_open_shell.json",
        {
            "functional": "lda,vwn5",
            "basis": "sto-3g",
            "grid_level": REFERENCE_GRID_LEVEL,
            "systems": systems,
            "atoms": atoms,
        },
    )


def flat(matrix) -> list[float]:
    return [float(x) for x in np.asarray(matrix).ravel()]


def dump(filename: str, payload: dict) -> None:
    DATA.mkdir(parents=True, exist_ok=True)
    path = DATA / filename
    path.write_text(json.dumps(payload, indent=1, sort_keys=True) + "\n")
    print(f"wrote {path.relative_to(ROOT)} ({path.stat().st_size / 1024:.0f} kB)")


def main() -> None:
    write_sto3g()
    write_lebedev()
    write_xc()

    integral_reference("h2_sto3g", "h2", "sto-3g", cart=False, full_eri=True)
    integral_reference("h2o_sto3g", "h2o_distorted", "sto-3g", cart=False, full_eri=True)
    integral_reference("h2s_sto3g", "h2s", "sto-3g", cart=False, full_eri=False)
    integral_reference("co2_sto3g", "co2", "sto-3g", cart=False, full_eri=False)
    # d functions are unused by STO-3G but the integral code is general; this
    # guards the l=2 path for a future 6-31G* switch.
    integral_reference("h2o_631gs", "h2o_distorted", "6-31G*", cart=True, full_eri=False)

    for key, name in [
        ("h2", "h2"),
        ("h2o", "h2o"),
        ("ch4", "ch4"),
        ("nh3", "nh3"),
        ("h2s", "h2s"),
        ("co2", "co2"),
    ]:
        scf_reference(key, name)
    scf_reference("benzene", "benzene", with_density=False)
    atomic_reference()
    open_shell_reference()


if __name__ == "__main__":
    main()
