//! 6-31G* contraction data for H-Ar.
//!
//! GENERATED by `scripts/gen_reference.py` from the 6-31G* definition
//! shipped with PySCF (Hariharan and Pople, Theor. Chim. Acta 28, 213
//! (1973) for H-Ne; Francl et al., J. Chem. Phys. 77, 3654 (1982) for
//! Na-Ar). Do not edit by hand.
//!
//! The d shells are the six-component Cartesian ones the basis was
//! defined with, which is what the engine builds. H and He carry no
//! polarisation functions (that would be 6-31G**).
//!
//! Coefficients multiply *normalised* primitive Gaussians, which is the
//! convention of the published tables; `Shell` applies that normalisation
//! and then renormalises the contracted function.

use super::ShellDef;

/// Shell definitions for each element, indexed by `z - 1`.
pub static B631GS: [&[ShellDef]; 18] = [
    // H
    &[
        ShellDef { l: 0, exponents: &[18.731137, 2.8253937, 0.6401217], coefficients: &[0.0334946, 0.23472695, 0.81375733] },
        ShellDef { l: 0, exponents: &[0.1612778], coefficients: &[1.0] },
    ],
    // He
    &[
        ShellDef { l: 0, exponents: &[38.421634, 5.77803, 1.241774], coefficients: &[0.023766, 0.154679, 0.46963] },
        ShellDef { l: 0, exponents: &[0.297964], coefficients: &[1.0] },
    ],
    // Li
    &[
        ShellDef { l: 0, exponents: &[642.41892, 96.798515, 22.091121, 6.2010703, 1.9351177, 0.6367358], coefficients: &[0.0021426, 0.0162089, 0.0773156, 0.245786, 0.470189, 0.3454708] },
        ShellDef { l: 0, exponents: &[2.3249184, 0.6324306, 0.0790534], coefficients: &[-0.0350917, -0.1912328, 1.0839878] },
        ShellDef { l: 0, exponents: &[0.035962], coefficients: &[1.0] },
        ShellDef { l: 1, exponents: &[2.3249184, 0.6324306, 0.0790534], coefficients: &[0.0089415, 0.1410095, 0.9453637] },
        ShellDef { l: 1, exponents: &[0.035962], coefficients: &[1.0] },
        ShellDef { l: 2, exponents: &[0.2], coefficients: &[1.0] },
    ],
    // Be
    &[
        ShellDef { l: 0, exponents: &[1264.5857, 189.93681, 43.159089, 12.098663, 3.8063232, 1.2728903], coefficients: &[0.0019448, 0.0148351, 0.0720906, 0.2371542, 0.4691987, 0.3565202] },
        ShellDef { l: 0, exponents: &[3.1964631, 0.7478133, 0.2199663], coefficients: &[-0.1126487, -0.2295064, 1.1869167] },
        ShellDef { l: 0, exponents: &[0.0823099], coefficients: &[1.0] },
        ShellDef { l: 1, exponents: &[3.1964631, 0.7478133, 0.2199663], coefficients: &[0.0559802, 0.2615506, 0.7939723] },
        ShellDef { l: 1, exponents: &[0.0823099], coefficients: &[1.0] },
        ShellDef { l: 2, exponents: &[0.4], coefficients: &[1.0] },
    ],
    // B
    &[
        ShellDef { l: 0, exponents: &[2068.8823, 310.64957, 70.683033, 19.86108, 6.2993048, 2.127027], coefficients: &[0.0018663, 0.0142515, 0.0695516, 0.2325729, 0.4670787, 0.3634314] },
        ShellDef { l: 0, exponents: &[4.727971, 1.1903377, 0.3594117], coefficients: &[-0.1303938, -0.1307889, 1.1309444] },
        ShellDef { l: 0, exponents: &[0.1267512], coefficients: &[1.0] },
        ShellDef { l: 1, exponents: &[4.727971, 1.1903377, 0.3594117], coefficients: &[0.0745976, 0.3078467, 0.7434568] },
        ShellDef { l: 1, exponents: &[0.1267512], coefficients: &[1.0] },
        ShellDef { l: 2, exponents: &[0.6], coefficients: &[1.0] },
    ],
    // C
    &[
        ShellDef { l: 0, exponents: &[3047.5249, 457.36951, 103.94869, 29.210155, 9.286663, 3.163927], coefficients: &[0.0018347, 0.0140373, 0.0688426, 0.2321844, 0.4679413, 0.362312] },
        ShellDef { l: 0, exponents: &[7.8682724, 1.8812885, 0.5442493], coefficients: &[-0.1193324, -0.1608542, 1.1434564] },
        ShellDef { l: 0, exponents: &[0.1687144], coefficients: &[1.0] },
        ShellDef { l: 1, exponents: &[7.8682724, 1.8812885, 0.5442493], coefficients: &[0.0689991, 0.316424, 0.7443083] },
        ShellDef { l: 1, exponents: &[0.1687144], coefficients: &[1.0] },
        ShellDef { l: 2, exponents: &[0.8], coefficients: &[1.0] },
    ],
    // N
    &[
        ShellDef { l: 0, exponents: &[4173.511, 627.4579, 142.9021, 40.23433, 12.82021, 4.390437], coefficients: &[0.0018348, 0.013995, 0.068587, 0.232241, 0.46907, 0.360455] },
        ShellDef { l: 0, exponents: &[11.626358, 2.71628, 0.772218], coefficients: &[-0.114961, -0.169118, 1.145852] },
        ShellDef { l: 0, exponents: &[0.2120313], coefficients: &[1.0] },
        ShellDef { l: 1, exponents: &[11.626358, 2.71628, 0.772218], coefficients: &[0.06758, 0.323907, 0.740895] },
        ShellDef { l: 1, exponents: &[0.2120313], coefficients: &[1.0] },
        ShellDef { l: 2, exponents: &[0.8], coefficients: &[1.0] },
    ],
    // O
    &[
        ShellDef { l: 0, exponents: &[5484.6717, 825.23495, 188.04696, 52.9645, 16.89757, 5.7996353], coefficients: &[0.0018311, 0.0139501, 0.0684451, 0.2327143, 0.470193, 0.3585209] },
        ShellDef { l: 0, exponents: &[15.539616, 3.5999336, 1.0137618], coefficients: &[-0.1107775, -0.1480263, 1.130767] },
        ShellDef { l: 0, exponents: &[0.2700058], coefficients: &[1.0] },
        ShellDef { l: 1, exponents: &[15.539616, 3.5999336, 1.0137618], coefficients: &[0.0708743, 0.3397528, 0.7271586] },
        ShellDef { l: 1, exponents: &[0.2700058], coefficients: &[1.0] },
        ShellDef { l: 2, exponents: &[0.8], coefficients: &[1.0] },
    ],
    // F
    &[
        ShellDef { l: 0, exponents: &[7001.71309, 1051.36609, 239.28569, 67.3974453, 21.5199573, 7.4031013], coefficients: &[0.0018196169, 0.0139160796, 0.0684053245, 0.23318576, 0.471267439, 0.356618546] },
        ShellDef { l: 0, exponents: &[20.8479528, 4.80830834, 1.34406986], coefficients: &[-0.108506975, -0.146451658, 1.12868858] },
        ShellDef { l: 0, exponents: &[0.358151393], coefficients: &[1.0] },
        ShellDef { l: 1, exponents: &[20.8479528, 4.80830834, 1.34406986], coefficients: &[0.0716287243, 0.345912103, 0.722469957] },
        ShellDef { l: 1, exponents: &[0.358151393], coefficients: &[1.0] },
        ShellDef { l: 2, exponents: &[0.8], coefficients: &[1.0] },
    ],
    // Ne
    &[
        ShellDef { l: 0, exponents: &[8425.85153, 1268.5194, 289.621414, 81.859004, 26.2515079, 9.09472051], coefficients: &[0.0018843481, 0.0143368994, 0.0701096233, 0.237373266, 0.473007126, 0.348401241] },
        ShellDef { l: 0, exponents: &[26.532131, 6.10175501, 1.69627153], coefficients: &[-0.107118287, -0.146163821, 1.1277735] },
        ShellDef { l: 0, exponents: &[0.4458187], coefficients: &[1.0] },
        ShellDef { l: 1, exponents: &[26.532131, 6.10175501, 1.69627153], coefficients: &[0.0719095885, 0.349513372, 0.719940512] },
        ShellDef { l: 1, exponents: &[0.4458187], coefficients: &[1.0] },
        ShellDef { l: 2, exponents: &[0.8], coefficients: &[1.0] },
    ],
    // Na
    &[
        ShellDef { l: 0, exponents: &[9993.2, 1499.89, 341.951, 94.6797, 29.7345, 10.0063], coefficients: &[0.0019377, 0.014807, 0.072706, 0.252629, 0.493242, 0.313169] },
        ShellDef { l: 0, exponents: &[150.963, 35.5878, 11.1683, 3.90201, 1.38177, 0.466382], coefficients: &[-0.0035421, -0.043959, -0.1097521, 0.187398, 0.646699, 0.306058] },
        ShellDef { l: 0, exponents: &[0.497966, 0.084353, 0.066635], coefficients: &[-0.248503, -0.131704, 1.23352] },
        ShellDef { l: 0, exponents: &[0.0259544], coefficients: &[1.0] },
        ShellDef { l: 1, exponents: &[150.963, 35.5878, 11.1683, 3.90201, 1.38177, 0.466382], coefficients: &[0.0050017, 0.035511, 0.142825, 0.33862, 0.451579, 0.273271] },
        ShellDef { l: 1, exponents: &[0.497966, 0.084353, 0.066635], coefficients: &[-0.023023, 0.950359, 0.059858] },
        ShellDef { l: 1, exponents: &[0.0259544], coefficients: &[1.0] },
        ShellDef { l: 2, exponents: &[0.175], coefficients: &[1.0] },
    ],
    // Mg
    &[
        ShellDef { l: 0, exponents: &[11722.8, 1759.93, 400.846, 112.807, 35.9997, 12.1828], coefficients: &[0.0019778, 0.015114, 0.073911, 0.249191, 0.487928, 0.319662] },
        ShellDef { l: 0, exponents: &[189.18, 45.2119, 14.3563, 5.13886, 1.90652, 0.705887], coefficients: &[-0.0032372, -0.041008, -0.1126, 0.148633, 0.616497, 0.364829] },
        ShellDef { l: 0, exponents: &[0.92934, 0.269035, 0.117379], coefficients: &[-0.21229, -0.107985, 1.17584] },
        ShellDef { l: 0, exponents: &[0.0421061], coefficients: &[1.0] },
        ShellDef { l: 1, exponents: &[189.18, 45.2119, 14.3563, 5.13886, 1.90652, 0.705887], coefficients: &[0.0049281, 0.034989, 0.140725, 0.333642, 0.44494, 0.269254] },
        ShellDef { l: 1, exponents: &[0.92934, 0.269035, 0.117379], coefficients: &[-0.022419, 0.19227, 0.846181] },
        ShellDef { l: 1, exponents: &[0.0421061], coefficients: &[1.0] },
        ShellDef { l: 2, exponents: &[0.175], coefficients: &[1.0] },
    ],
    // Al
    &[
        ShellDef { l: 0, exponents: &[13983.1, 2098.75, 477.705, 134.36, 42.8709, 14.5189], coefficients: &[0.00194267, 0.0148599, 0.0728494, 0.24683, 0.487258, 0.323496] },
        ShellDef { l: 0, exponents: &[239.668, 57.4419, 18.2859, 6.59914, 2.49049, 0.94454], coefficients: &[-0.00292619, -0.037408, -0.114487, 0.115635, 0.612595, 0.393799] },
        ShellDef { l: 0, exponents: &[1.2779, 0.39759, 0.160095], coefficients: &[-0.227606, 0.00144583, 1.09279] },
        ShellDef { l: 0, exponents: &[0.0556577], coefficients: &[1.0] },
        ShellDef { l: 1, exponents: &[239.668, 57.4419, 18.2859, 6.59914, 2.49049, 0.94454], coefficients: &[0.00460285, 0.033199, 0.136282, 0.330476, 0.449146, 0.265704] },
        ShellDef { l: 1, exponents: &[1.2779, 0.39759, 0.160095], coefficients: &[-0.017513, 0.244533, 0.804934] },
        ShellDef { l: 1, exponents: &[0.0556577], coefficients: &[1.0] },
        ShellDef { l: 2, exponents: &[0.325], coefficients: &[1.0] },
    ],
    // Si
    &[
        ShellDef { l: 0, exponents: &[16115.9, 2425.58, 553.867, 156.34, 50.0683, 17.0178], coefficients: &[0.00195948, 0.0149288, 0.0728478, 0.24613, 0.485914, 0.325002] },
        ShellDef { l: 0, exponents: &[292.718, 69.8731, 22.3363, 8.15039, 3.13458, 1.22543], coefficients: &[-0.00278094, -0.0357146, -0.114985, 0.0935634, 0.603017, 0.418959] },
        ShellDef { l: 0, exponents: &[1.72738, 0.572922, 0.222192], coefficients: &[-0.24463, 0.00431572, 1.09818] },
        ShellDef { l: 0, exponents: &[0.0778369], coefficients: &[1.0] },
        ShellDef { l: 1, exponents: &[292.718, 69.8731, 22.3363, 8.15039, 3.13458, 1.22543], coefficients: &[0.00443826, 0.0326679, 0.134721, 0.328678, 0.44964, 0.261372] },
        ShellDef { l: 1, exponents: &[1.72738, 0.572922, 0.222192], coefficients: &[-0.0177951, 0.253539, 0.800669] },
        ShellDef { l: 1, exponents: &[0.0778369], coefficients: &[1.0] },
        ShellDef { l: 2, exponents: &[0.45], coefficients: &[1.0] },
    ],
    // P
    &[
        ShellDef { l: 0, exponents: &[19413.3, 2909.42, 661.364, 185.759, 59.1943, 20.031], coefficients: &[0.0018516, 0.0142062, 0.0699995, 0.240079, 0.484762, 0.3352] },
        ShellDef { l: 0, exponents: &[339.478, 81.0101, 25.878, 9.45221, 3.66566, 1.46746], coefficients: &[-0.00278217, -0.0360499, -0.116631, 0.0968328, 0.614418, 0.403798] },
        ShellDef { l: 0, exponents: &[2.15623, 0.748997, 0.283145], coefficients: &[-0.252923, 0.0328517, 1.08125] },
        ShellDef { l: 0, exponents: &[0.0998317], coefficients: &[1.0] },
        ShellDef { l: 1, exponents: &[339.478, 81.0101, 25.878, 9.45221, 3.66566, 1.46746], coefficients: &[0.00456462, 0.0336936, 0.139755, 0.339362, 0.450921, 0.238586] },
        ShellDef { l: 1, exponents: &[2.15623, 0.748997, 0.283145], coefficients: &[-0.0177653, 0.274058, 0.785421] },
        ShellDef { l: 1, exponents: &[0.0998317], coefficients: &[1.0] },
        ShellDef { l: 2, exponents: &[0.55], coefficients: &[1.0] },
    ],
    // S
    &[
        ShellDef { l: 0, exponents: &[21917.1, 3301.49, 754.146, 212.711, 67.9896, 23.0515], coefficients: &[0.001869, 0.01423, 0.069696, 0.238487, 0.483307, 0.338074] },
        ShellDef { l: 0, exponents: &[423.735, 100.71, 32.1599, 11.8079, 4.6311, 1.87025], coefficients: &[-0.0023767, -0.031693, -0.113317, 0.05609, 0.592255, 0.455006] },
        ShellDef { l: 0, exponents: &[2.61584, 0.922167, 0.341287], coefficients: &[-0.250374, 0.066957, 1.05451] },
        ShellDef { l: 0, exponents: &[0.117167], coefficients: &[1.0] },
        ShellDef { l: 1, exponents: &[423.735, 100.71, 32.1599, 11.8079, 4.6311, 1.87025], coefficients: &[0.004061, 0.030681, 0.130452, 0.327205, 0.452851, 0.256042] },
        ShellDef { l: 1, exponents: &[2.61584, 0.922167, 0.341287], coefficients: &[-0.014511, 0.310263, 0.754483] },
        ShellDef { l: 1, exponents: &[0.117167], coefficients: &[1.0] },
        ShellDef { l: 2, exponents: &[0.65], coefficients: &[1.0] },
    ],
    // Cl
    &[
        ShellDef { l: 0, exponents: &[25180.1, 3780.35, 860.474, 242.145, 77.3349, 26.247], coefficients: &[0.001833, 0.014034, 0.069097, 0.237452, 0.483034, 0.339856] },
        ShellDef { l: 0, exponents: &[491.765, 116.984, 37.4153, 13.7834, 5.45215, 2.22588], coefficients: &[-0.0022974, -0.030714, -0.112528, 0.045016, 0.589353, 0.465206] },
        ShellDef { l: 0, exponents: &[3.18649, 1.14427, 0.420377], coefficients: &[-0.25183, 0.061589, 1.06018] },
        ShellDef { l: 0, exponents: &[0.142657], coefficients: &[1.0] },
        ShellDef { l: 1, exponents: &[491.765, 116.984, 37.4153, 13.7834, 5.45215, 2.22588], coefficients: &[0.0039894, 0.030318, 0.12988, 0.327951, 0.453527, 0.252154] },
        ShellDef { l: 1, exponents: &[3.18649, 1.14427, 0.420377], coefficients: &[-0.014299, 0.323572, 0.743507] },
        ShellDef { l: 1, exponents: &[0.142657], coefficients: &[1.0] },
        ShellDef { l: 2, exponents: &[0.75], coefficients: &[1.0] },
    ],
    // Ar
    &[
        ShellDef { l: 0, exponents: &[28348.3, 4257.62, 969.857, 273.263, 87.3695, 29.6867], coefficients: &[0.00182526, 0.0139686, 0.0687073, 0.236204, 0.482214, 0.342043] },
        ShellDef { l: 0, exponents: &[575.891, 136.816, 43.8098, 16.2094, 6.46084, 2.65114], coefficients: &[-0.00215972, -0.0290775, -0.110827, 0.0276999, 0.577613, 0.488688] },
        ShellDef { l: 0, exponents: &[3.86028, 1.41373, 0.516646], coefficients: &[-0.255592, 0.0378066, 1.08056] },
        ShellDef { l: 0, exponents: &[0.173888], coefficients: &[1.0] },
        ShellDef { l: 1, exponents: &[575.891, 136.816, 43.8098, 16.2094, 6.46084, 2.65114], coefficients: &[0.00380665, 0.0292305, 0.126467, 0.32351, 0.454896, 0.25663] },
        ShellDef { l: 1, exponents: &[3.86028, 1.41373, 0.516646], coefficients: &[-0.0159197, 0.324646, 0.74399] },
        ShellDef { l: 1, exponents: &[0.173888], coefficients: &[1.0] },
        ShellDef { l: 2, exponents: &[0.85], coefficients: &[1.0] },
    ],
];
